/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GraphicsRouteImport } from './routes/graphics'
import { Route as PhotoRouteImport } from './routes/photo'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as VideoRouteImport } from './routes/video'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GraphicsRoute = GraphicsRouteImport.update({
  id: '/graphics',
  path: '/graphics',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotoRoute = PhotoRouteImport.update({
  id: '/photo',
  path: '/photo',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const VideoRoute = VideoRouteImport.update({
  id: '/video',
  path: '/video',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/photo': typeof PhotoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/photo': typeof PhotoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/graphics': typeof GraphicsRoute
  '/photo': typeof PhotoRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/video': typeof VideoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/graphics' | '/photo' | '/sitemap.xml' | '/video'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/graphics' | '/photo' | '/sitemap.xml' | '/video'
  id: '__root__' | '/' | '/graphics' | '/photo' | '/sitemap.xml' | '/video'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GraphicsRoute: typeof GraphicsRoute
  PhotoRoute: typeof PhotoRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  VideoRoute: typeof VideoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/graphics': {
      id: '/graphics'
      path: '/graphics'
      fullPath: '/graphics'
      preLoaderRoute: typeof GraphicsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photo': {
      id: '/photo'
      path: '/photo'
      fullPath: '/photo'
      preLoaderRoute: typeof PhotoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/video': {
      id: '/video'
      path: '/video'
      fullPath: '/video'
      preLoaderRoute: typeof VideoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GraphicsRoute: GraphicsRoute,
  PhotoRoute: PhotoRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  VideoRoute: VideoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
